# WhatATheme
markdown: kramdown

# URL of the Site
url: 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Md. Mehedi Hasan Akash
# Description of the Site
description: SOFTWARE ENGINEER · AEROSPACE TECHNOLOGY ENTHUSIAST
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mehaakmehi@gmail.com
facebook_username: MehediMehi
twitter_username: MehediMehi
instagram_username: mehedimehi
linkedin_username: mehedimehi
github_username:  MehediMehi
youtube_channel_id: UC3YRRpLKaTEMycAsPgDiYJg
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
# google-analytics: 

# Disqus
disqus-shortname: Mehedi

# Name of the Author
author-name: Md. Mehedi Hasan Akash
# URL for the Image of the Author
author-image: /WhatATheme/assets/images/author.jpg
# 60 Words About the Author
author-about: Current Specialist at Robi Axiata Limited. Three years and ten+ months of experience specializing in Backend Development, Infrastructure Automation, Machine Learning and Project Management. A super nerd who loves Linux and OS X and enjoys customizing all of the development environments. Interested in devising a better problem-solving method for challenging tasks and learning new technologies and tools if the need arises. Have an interest in Space Technology, Aerospace Engineering, Self-Driving Car Technology, Bicycling etc.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/MehediMehi

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
